AE:
  IS: true
  decoder: diffusion
  encoder: pointnet
  t: 50
  truncate: true
ATTACK:
  EPS: 0.05
  ITER: 200
  METHOD: add
DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: non_adaptive_pointnet2_truncate_diffusion_add_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointnet2
  SEED: 1
  TASK: non_adaptive_attack_cls
TRAIN:
  l2: 1e-4
