DATALOADER:
  batch_size: 64
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: pointnet_truncate_diffusion_add_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointnet
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: true
  encoder: 'pointnet'
  decoder: 'diffusion'
  truncate: true
  t: 30
ATTACK:
  METHOD: 'add'
  ITER: 200
  LOSS: 'feature'
  EPS: 0.05