AE:
  IS: true
  decoder: diffusion
  encoder: pointnet
  t: 50
  truncate: true
ATTACK:
  METHOD: si_adv
DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_si_adv_diffusion # 
  EXP_ID: non_adaptive_pointnet_truncated_diffusion_si_adv
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointnet
  SEED: 1
  TASK: si_adv_attack_cls
