DATALOADER:
  batch_size: 128
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: pct_diffusion_nattack_l2_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pct
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: true
  truncate: True
  encoder: 'pointnet'
  decoder: 'diffusion'
  t: 30
ATTACK:
  METHOD: 'nattack'
  ITER: 100
  EPS: 1.25
  NORM: 2.