DATALOADER:
  batch_size: 64
  num_workers: 8
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: dgcnn_cls_ae_diffusion_step_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 1
  TASK: cls
  OPTIMIZER: step
TRAIN:
  l2: 1e-4
AE:
  IS: true
  encoder: 'pointnet'
  decoder: 'diffusion'