DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: pct_cls_ae_diffusion_pct_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pct
  SEED: 1
  TASK: cls
  OPTIMIZER: pct
TRAIN:
  l2: 1e-4
  learning_rate: 0.0001
AE:
  IS: true
  encoder: 'pointnet'
  decoder: 'diffusion'