AE:
  IS: true
  decoder: diffusion
  encoder: pointnet
  t: 50
  truncate: true
DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: pointnet2_cls_ae_diffusion_step_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointnet2
  OPTIMIZER: step
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
