AE:
  IS: true
  decoder: diffusion
  encoder: pointnet
  t: 50
  truncate: true
ATTACK:
  ITER: 40
  METHOD: drop
DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: non_adaptive_pointMLP_truncate_diffusion_drop_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointMLP
  SEED: 1
  TASK: non_adaptive_attack_cls
TRAIN:
  l2: 1e-4
