AE:
  IS: true
  decoder: diffusion
  encoder: pointnet
  t: 35
  truncate: true
ATTACK:
  METHOD: 'advpc'
  ITER: 200
  EPS: 0.05
DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: ScanObjectNN_diffusion
  EXP_ID: non_adaptive_dgcnn_diffusion_advpc_ScanObjectNN_diffusion
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 1
  TASK: non_adaptive_attack_cls
TRAIN:
  l2: 1e-4
