AE:
  IS: true
  decoder: diffusion
  encoder: pointnet
  t: 35
  truncate: true
ATTACK:
  EPS: 0.05
  ITER: 200
  METHOD: pgd
DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: ScanObjectNN_diffusion
  EXP_ID: non_adaptive_pct_diffusion_pgd_ScanObjectNN_diffusion
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pct
  SEED: 1
  TASK: non_adaptive_attack_cls
TRAIN:
  l2: 1e-4
