AE:
  IS: true
  decoder: diffusion
  encoder: pointnet
  t: 35
  truncate: true
ATTACK:
  METHOD: 'pgd'
  ITER: 200
  EPS: 1.25
  NORM: 2.
DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: ScanObjectNN_diffusion
  EXP_ID: non_adaptive_pointnet2_diffusion_pgdl2_ScanObjectNN_diffusion
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointnet2
  SEED: 1
  TASK: non_adaptive_attack_cls
TRAIN:
  l2: 1e-4
