DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: advpc_curvenet_truncate_diffusion_pgd_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: curvenet
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: true
  encoder: 'pointnet'
  decoder: 'diffusion'
  truncate: true
  t: 30
ATTACK:
  METHOD: 'advpc'
  ITER: 200
  EPS: 0.05