DATALOADER:
  batch_size: 128
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: dgcnn_nattack_linf_2
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 2
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: False
ATTACK:
  METHOD: 'nattack'
  ITER: 100