DATALOADER:
  batch_size: 128
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: dgcnn_diffusion_spsa_linf_1
  LOSS_NAME: cross_entropy
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 1
  TASK: non_adaptive_attack_cls
#  TASK: cls_trans
TRAIN:
  l2: 1e-4
AE:
  IS: true
  truncate: True
  encoder: 'pointnet'
  decoder: 'diffusion'
  t: 30
ATTACK:
  METHOD: 'spsa'
  ITER: 100