DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: dgcnn_diffusion_cw_l2_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: true
  encoder: 'pointnet'
  decoder: 'diffusion'
ATTACK:
  METHOD: 'cw'
  ITER: 500
  NORM: 2.
  LOSS: 'feature'