DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: advpc_pct_truncated_diffusion_latent_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pct
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: true
  truncate: True
  encoder: 'pointnet'
  decoder: 'diffusion'
  t: 30
ATTACK:
  METHOD: 'advpc'
  ITER: 200
  LOSS: 'feature'
  EPS: 0.05