DATALOADER:
  batch_size: 128
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: pct_spsa_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pct
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: False
ATTACK:
  METHOD: 'spsa'
  ITER: 100