DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: pointMLP_pgd_l2_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointMLP
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: False
ATTACK:
  METHOD: 'pgd'
  ITER: 200
  EPS: 1.25
  NORM: 2.