DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: advpc_pointMLP_pgd_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointMLP
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AE:
  IS: False
ATTACK:
  METHOD: 'advpc'
  ITER: 200
  EPS: 0.05