DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_diffusion
  EXP_ID: sde_pointMLP_truncated_diffusion_pgd_linf_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: pointMLP
  SEED: 1
  TASK: sde
TRAIN:
  l2: 1e-4
AE:
  IS: true
  truncate: True
  encoder: 'pointnet'
  decoder: 'diffusion'
  t: 30
ATTACK:
  METHOD: 'pgd'
  ITER: 200
  EPS: 0.05